// <auto-generated />
using System;
using DevExpressReporting.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevExpressReporting.Migrations
{
    [DbContext(typeof(DataTransformDbContext))]
    [Migration("20240220192601_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevExpressReporting.Models.AdcCoreSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cl_Bal_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Diff_in_Open_Cls_Bal_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Differnce_A_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GlCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Op_Bal_A")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sum_of_Db_Cr_Summation_B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Trans_Count")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("credit_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("debit_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AdcCoreSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
